server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  #新增网关配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh             #路由ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/provider/payment/get/**      #断言，路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/provider/payment/lb/**
#            - After=2021-04-26T10:05:42.949+08:00[Asia/Shanghai]  #指定时间后才能访问(After)
#            - Before=2021-04-27T10:05:42.949+08:00[Asia/Shanghai]  #指定时间前才能访问(Before)
#            - Between=2021-04-26T10:05:42.949+08:00[Asia/Shanghai],2021-04-27T10:05:42.949+08:00[Asia/Shanghai]  #指定时间内才能访问(Between)
#            - Cookie=username,Blanc  #cookie
#            - Header=X-Request-Id,\d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.neui.cn
#            - Method=GET  #只允许get请求访问
#            - Query=username,^[a-z]{5}

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
