server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.232.134:8848

#消费者要去访问的微服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider