server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.232.134:8848  #配置Nacos地址

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"